"""add vpn accounts table

Revision ID: ac147065f8d8
Revises: 8fa641654e50
Create Date: 2026-08-02 20:21:54.638477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac147065f8d8'
down_revision: Union[str, Sequence[str], None] = '8fa641654e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('marzban_username', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('subscription_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_accounts_marzban_username'), 'vpn_accounts', ['marzban_username'], unique=True)
    op.create_index(op.f('ix_vpn_accounts_subscription_id'), 'vpn_accounts', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_accounts_subscription_id'), table_name='vpn_accounts')
    op.drop_index(op.f('ix_vpn_accounts_marzban_username'), table_name='vpn_accounts')
    op.drop_table('vpn_accounts')
    # ### end Alembic commands ###
